services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=gemma3:4b
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  image-server:
    build:
      context: ./image-server
    container_name: image-server
    ports:
      - "8000:8000"
    volumes:
      - ./image-server:/app
    env_file: ".env"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: >
      uvicorn server.__main__:app --reload --reload-dir /app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - ollama
      - image-server
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - ollama
      - mongodb
      - image-server
      - backend

volumes:
  ollama_data:
  mongo_data:
