import Header from "./components/Header";
import ChatHistory from "./components/ChatHistory";
import InputBar from "./components/InputBar";

const md = `

# Driftbot Prompt Graph: GitHub Pull Request Review

This memory file documents the prompt graph generated by Driftbot when handling a \`pull_request.opened\` event from GitHub. It illustrates a complete response pipeline involving classification, review, and follow-up story creation.

---

## 🧠 Graph Overview

### Event Type: \`github.pull_request.opened\`
### Source: GitHub Webhook
### Intent: Code Review and Task Generation

---

## 🔗 Prompt Graph

\`\`\`mermaid
graph TD;
    Event["PR Opened Event"]
    Classify["Classify PR Intent"]
    Review["Review PR Code"]
    Suggest["Generate Suggestions"]
    CreateStory["Create Linear Story"]

    Event --> Classify
    Classify --> Review
    Review --> Suggest
    Suggest --> CreateStory
\`\`\`

---

## 🧩 JSON Representation

\`\`\`json
{
  "id": "github.pr.opened",
  "type": "event",
  "inputs": {
    "source": "github",
    "event_type": "pull_request.opened"
  },
  "graph": [
    {
      "id": "classify-intent",
      "type": "prompt",
      "model": "gpt-3.5-turbo",
      "input": "event.body.pull_request.title + event.body.pull_request.body",
      "template": "classify_pr_intent"
    },
    {
      "id": "review-pr",
      "type": "prompt",
      "model": "gpt-4",
      "input": "event.body.pull_request.diff_url",
      "template": "review_code_diff",
      "after": ["classify-intent"]
    },
    {
      "id": "generate-suggestions",
      "type": "prompt",
      "model": "gpt-4",
      "input": "output.review-pr",
      "template": "suggest_code_changes",
      "after": ["review-pr"]
    },
    {
      "id": "create-story",
      "type": "action",
      "service": "linear",
      "action": "createStory",
      "input": {
        "title": "output.generate-suggestions.summary.title",
        "description": "output.generate-suggestions.summary.description"
      },
      "after": ["generate-suggestions"]
    }
  ]
}
\`\`\`

---

## 📜 YAML Representation

\`\`\`yaml
id: github.pr.opened
type: event
inputs:
  source: github
  event_type: pull_request.opened
graph:
  - id: classify-intent
    type: prompt
    model: gpt-3.5-turbo
    input: "{{ event.body.pull_request.title }} {{ event.body.pull_request.body }}"
    template: classify_pr_intent

  - id: review-pr
    type: prompt
    model: gpt-4
    input: "{{ event.body.pull_request.diff_url }}"
    template: review_code_diff
    after:
      - classify-intent

  - id: generate-suggestions
    type: prompt
    model: gpt-4
    input: "{{ output.review-pr }}"
    template: suggest_code_changes
    after:
      - review-pr

  - id: create-story
    type: action
    service: linear
    action: createStory
    input:
      title: "{{ output.generate-suggestions.summary.title }}"
      description: "{{ output.generate-suggestions.summary.description }}"
    after:
      - generate-suggestions
\`\`\`

---

## 🧠 Prompt Templates Used

### \`classify_pr_intent\`
\`\`\`txt
Classify the purpose of the following pull request:
Title: {{title}}
Body: {{body}}
Return one of: [bugfix, feature, refactor, chore, unknown]
\`\`\`

### \`review_code_diff\`
\`\`\`txt
Review the following code diff and highlight areas of concern or improvement:
{{diff_url}}
\`\`\`

### \`suggest_code_changes\`
\`\`\`txt
Based on this review, suggest improvements and generate a title/description summary for a task to track these changes.
{{review_text}}
Return in structured format:
- summary.title
- summary.description
\`\`\`

---

## ✅ Result

This graph enables Driftbot to:
- Immediately classify a PR's purpose
- Review changes with GPT-4
- Generate actionable feedback
- Create follow-up stories in Linear

Useful for PM augmentation and developer guidance during the review process.

`;

export default function App() {
  return (
    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100 dark">
      <Header title="Markdown Chat" />
      <ChatHistory
        responses={[md, md, md, md, md, md, md, md, md, md, md, md, md, md]}
      />
      <InputBar />
    </div>
  );
}
